const uuidv4 = require("uuid/v4");
const Hashids = require("hashids");
const URL = require("url").URL;
const hashids = new Hashids();
const { genJwtToken } = require("./jwt_helper");

const re = /(\S+)\s+(\S+)/;

// Note: express http converts all headers to lower case
const AUTH_HEADER = "authorization";
const BEARER_AUTH_SCHEME = "bearer";

function parseAuthHeader(hdrValue) {
  if (typeof hdrValue !== "string") {
    return null;
  }
  const matches = hdrValue.match(re);
  return matches && { scheme: matches[1], value: matches[2] };
}

const fromAuthHeaderWithScheme = function(authScheme) {
  const authSchemeLower = authScheme.toLowerCase();
  return function(request) {
    let token = null;
    if (request.headers[AUTH_HEADER]) {
      const authParams = parseAuthHeader(request.headers[AUTH_HEADER]);
      if (authParams && authSchemeLower === authParams.scheme.toLowerCase()) {
        token = authParams.value;
      }
    }
    return token;
  };
};

const fromAuthHeaderAsBearerToken = function() {
  return fromAuthHeaderWithScheme(BEARER_AUTH_SCHEME);
};

const appTokenFromRequest = fromAuthHeaderAsBearerToken();

// app token to validate the request is coming from the authenticated server only.
const appTokenDB = {
  sso_consumer: "l1Q7zkOL59cRqWBkQ12ZiGVW2DBL",
  simple_sso_consumer: "1g0jJwGmRQhJwvwNOrY4i90kD0m"
};

const alloweOrigin = {
  "http://consumer.ankuranand.in:3020": true,
  "http://consumertwo.ankuranand.in:3030": true,
  "http://sso.ankuranand.in:3080": false
};

const deHyphenatedUUID = () => uuidv4().replace(/-/gi, "");
const encodedId = () => hashids.encodeHex(deHyphenatedUUID());

// A temporary cahce to store all the application that has login using the current session.
// It can be useful for various audit purposes
const sessionUser = {};
const sessionApp = {};

const originAppName = {
  "http://consumer.ankuranand.in:3020": "sso_consumer",
  "http://consumertwo.ankuranand.in:3030": "simple_sso_consumer"
};

const userDB = {
  "info@ankuranand.com": {
    password: "test",
    userId: encodedId(),  // in case you don't want to share the user-email
    appPolicy: {
      sso_consumer: { role: "admin", shareEmail: true },
      simple_sso_consumer: { role: "user", shareEmail: false }
    }
  }
};

// these token are for the validation purpose
const intrmTokenCache = {};

const fillIntrmTokenCache = (origin, id, intrmToken) => {
  intrmTokenCache[intrmToken] = [id, originAppName[origin]];
};

const storeApplicationInCache = (origin, id, intrmToken) => {
  if (sessionApp[id] == null) {
    sessionApp[id] = {
      [originAppName[origin]]: true
    };
    fillIntrmTokenCache(origin, id, intrmToken);
  } else {
    sessionApp[id][originAppName[origin]] = true;
    fillIntrmTokenCache(origin, id, intrmToken);
  }
  console.log({ ...sessionApp }, { ...sessionUser }, { intrmTokenCache });
};

/**
 * Generate sso user's details to be shared with the application.
 * The application can take the sso user's details and log in
 * the corresponding user in the application.
 *
 * @param {string} ssoToken
 * @returns user details to be shared with the application
 */
const generatePayload = ssoToken => {
  const globalSessionToken = intrmTokenCache[ssoToken][0];
  const appName = intrmTokenCache[ssoToken][1];
  const userEmail = sessionUser[globalSessionToken];
  const user = userDB[userEmail];
  const appPolicy = user.appPolicy[appName];
  const email = appPolicy.shareEmail === true ? userEmail : undefined;
  const payload = {
    ...{ ...appPolicy },
    ...{
      email,
      shareEmail: undefined,
      uid: user.userId,
      // global SessionID for the logout functionality.
      globalSessionID: globalSessionToken
    }
  };
  return payload;
};

const verifySsoToken = async (req, res, next) => {
  // The application token represents a application registered with the sso server
  const appToken = appTokenFromRequest(req);
  // The sso token represents a valid sso session created by the sso server
  const { ssoToken } = req.query;

  // At this point both the application token and sso token must be prrovided.
  if (
    appToken == null ||
    ssoToken == null ||
    intrmTokenCache[ssoToken] == null
  ) {
    return res.status(400).json({ message: "badRequest" });
  }

  // Also, both the application token and sso token must be valid.
  // This mean the application token must be registered with the sso server
  // and the sso token must be generated by the sso server.
  const appName = intrmTokenCache[ssoToken][1];
  const globalSessionToken = intrmTokenCache[ssoToken][0];
  if (
    appToken !== appTokenDB[appName] ||
    sessionApp[globalSessionToken][appName] !== true
  ) {
    return res.status(403).json({ message: "Unauthorized" });
  }

  // checking if the token passed has been generated
  const payload = generatePayload(ssoToken);

  const token = await genJwtToken(payload);
  // delete the itremCache key for no futher use,
  delete intrmTokenCache[ssoToken];
  return res.status(200).json({ token });
};

/**
 * The sso server does the login and redirect to the application.
 * The sso server does not give out the user credentials to the application
 * right away. It gives out a token which can be used to fetch the user.
 */
const doLogin = (req, res, next) => {
  // Validate email and password, hard coded for now.
  const { email, password } = req.body;
  if (!(userDB[email] && password === userDB[email].password)) {
    return res.status(404).json({ message: "Invalid email and password" });
  }

  // Email and password validated, create user session on sso server
  const id = encodedId();
  req.session.user = id;
  sessionUser[id] = email;

  // Without redirect url, go to sso home page
  const { serviceURL } = req.query;
  if (serviceURL == null) {
    return res.redirect("/");
  }

  // With redirect url, redirect to the consumer application
  // and provide an sso token to fetch more user credentials
  const url = new URL(serviceURL);
  const intrmid = encodedId();
  storeApplicationInCache(url.origin, id, intrmid);
  return res.redirect(`${serviceURL}?ssoToken=${intrmid}`);
};

/**
 * The consumer calls this to initialize the login flow with the SSO server.
 * If the user has not been logged in, the user will be redirected to the login page.
 */
const login = (req, res, next) => {
  // The req.query will have the redirect url where we need to redirect after successful
  // login and with sso token.
  // This can also be used to verify the origin from where the request has came in
  // for the redirection
  const { serviceURL } = req.query;

  // direct access will give the error inside new URL.
  if (serviceURL != null) {
    const url = new URL(serviceURL);

    // Allow sso login from certain origin urls only
    if (alloweOrigin[url.origin] !== true) {
      return res
        .status(400)
        .json({ message: `Your origin ${url.origin} are not allowed to access the sso-server` });
    }
  }

  // Already logged in without a redirect url, go to sso home page
  if (req.session.user != null && serviceURL == null) {
    return res.redirect("/");
  }

  // Already loggin in with a redirect url, redirect to the url and provide
  // an sso token for further retrival of sso user credentials
  if (req.session.user != null && serviceURL != null) {
    const url = new URL(serviceURL);
    const intrmid = encodedId();
    storeApplicationInCache(url.origin, req.session.user, intrmid);
    return res.redirect(`${serviceURL}?ssoToken=${intrmid}`);
  }

  // Else, user has not logged in sso server, show the sso login page
  return res.render("login", {
    title: "SSO-Server | Login"
  });
};

module.exports = Object.assign({}, { doLogin, login, verifySsoToken });
